### ISSUE TITLE
Support for latter httpx

### ISSUE THREAD

**Issue by fabaff** [fredrike/pypoint#10]
There is a new `httpx` release available. From a distribution point of view it's preferred to ship the latest release and pypoint seems to pin `httpx`. Home Assistant will also soon require `httpx==0.20.0`.

Is there any reason for the pinning or can the pin be relaxed?

Perhaps switch from pinning to something like `httpx>=0.19.0,<1` could reduce the maintenance burden. I guess that `authlib` would break anyway if there is an issue with the `httpx` release.

**Comment by fredrike** [comment]
Thanks for making me aware of this.
