### ISSUE TITLE
V1 Endpoints will be paginated

### ISSUE THREAD

**Issue by Aidenir** [fredrike/pypoint#8]
Hi Fredrik,

I just wanted to inform you that we intend to make the v1 endpoints of our api paginated in the near future. We recommend you start using the v5 endpoints, docs can be found at [https://api.minut.com/latest/docs/ ](https://api.minut.com/latest/docs/ )

Given that most users who are using this integration does not have more than 10 homes or devices (the default limits) it probably shouldn't affect anything, but for the users with more than this some devices could be missing if the pagination is not implemented.

Best regards,
Viktor from Minut

**Comment by fredrike** [comment]
Ah, nice to know! But are you deprecating and closing the `v1` endpoint all together?

It would be super if the sensor-readings also contained pagination. Now I'm sending `limit: 1` but I don't think that is supported:

https://github.com/fredrike/pypoint/blob/a6bbd6e29ee3787f94f96d9835acb2223f4d152d/pypoint/__init__.py#L160-L168

**Comment by Aidenir** [comment]
We won't be closing them entirely, just adding default pagination values (thereby breaking them for users with loads of homes or devices).

Having pagination on the sensor-readings is something we have on our roadmap, but at the moment it's not very high-priority so I cannot say when it will be added unfortunately.

**Comment by Gyran** [comment]
Got an email now that v1 will be shut down on 15th of October. So we would need to update to the latest API. @Aidenir where can we read what the breaking changes are to the API so know more specifically what we need to do?

**Comment by Gyran** [comment]
Did some testing and v1 only returns active devices when listing devices but v5 returns all devices that I've had. Other than that it seems to be more or less compatible from what I can see with my quick test.. Just have to ignore the not active ones.

**Comment by fredrike** [comment]
Fixed in v2.2.0 https://github.com/fredrike/pypoint/commit/a2caa0da2d327e2170a21d5cc93e1fd490cbfd4b
